Repository ceph/pulpito-ng, pull requests merged in 2023-07, with the labels that each got.

#24 pages/Job/index.js: fix job started time
  src/pages/Job/index.js
Labels: bug

#25 Implement kill-run button
  src/pages/Run/index.tsx
Labels: feature

#30 pages/Runs/index.tsx: fixed date filter box alignment
  src/pages/Runs/index.tsx
Labels: bug

#22 Init Dockerfile & containerized pulpito-ng
  .dockerignore
  Dockerfile
  README.md
  package.json
  vite.config.js
Labels: documentation, enhancement
