Repository ceph/pulpito-ng, pull requests merged in 2023-06, with the labels that each got.

#15 lib/utils.js: changed year format from yy to yyyy
  src/lib/utils.js
Labels: bug

#18 added sentry icon
  src/components/JobList/assets/sentry.svg
  src/components/JobList/index.js
Labels: bug

#19 .github/workflows/deploy.yml: run CI on every PR
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  package.json
Labels: CI/CD

#21 Add routes for backwards compatibility
  src/App.tsx
Labels: enhancement
