Repository ceph/pulpito-ng, pull requests merged in 2023-08, with the labels that each got.

#44 Job: Add missing key prop to node links
  src/pages/Job/index.jsx
Labels: bug

#56 add rewrite rule for netlify
  public/_redirects
Labels: CI/CD

#53 Dockerfile: Run in production mode
  Dockerfile
  vite.config.js
Labels: enhancement

#46 Add /nodes pages
  src/App.tsx
  src/components/DataGrid/index.jsx
  src/components/Drawer/index.jsx
  src/components/JobList/index.tsx
  src/components/NodeList/index.tsx
  src/lib/paddles.d.ts
  src/lib/paddles.ts
  src/pages/Node/index.tsx
  src/pages/Nodes/index.tsx
  src/pages/Run/index.tsx
  src/pages/StatsNodesJobs/index.tsx
  src/pages/StatsNodesLock/index.tsx
Labels: feature

#38 JobList: Hover on status col shows failure reason
  src/components/JobList/index.tsx
Labels: feature

#37 Job{,List}: Link to job archive directories
  src/components/JobList/index.tsx
  src/lib/utils.js
  src/pages/Job/index.jsx
Labels: enhancement
