Repository ceph/pulpito-ng, pull requests merged in 2023-09, with the labels that each got.

#52 Github Authentication
  package-lock.json
  package.json
  src/components/AppBar/index.jsx
  src/components/Login/index.jsx
  src/index.tsx
  src/lib/teuthologyAPI.ts
Labels: feature

#58 fix: default url for TEUTHOLOGY_API_SERVER
  src/components/Login/index.jsx
  src/lib/teuthologyAPI.ts
Labels: bug

#59 Fix breakage if teuthology-api endpoint is unconfigured
  src/components/Login/index.jsx
  src/lib/teuthologyAPI.ts
Labels: enhancement
